name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    services:
      pg_forumapi_test:
        image: prasetyaip/ems-postgresql:v1
        env:
          POSTGRES_USER: ${{ secrets.PGUSER_TEST }}
          POSTGRES_PASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          POSTGRES_DB: ${{ secrets.PGDATABASE_TEST }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5433:5432

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v3
      - name: Check docker run
        run: |
          docker -v
          docker ps
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install migrate and test
        run: |
          npm install
          npm run migrate:test up
          npm run test
        env:
          CI: true
          PGHOST_TEST: ${{ secrets.PGHOST_TEST }}
          PGUSER_TEST: ${{ secrets.PGUSER_TEST }}
          PGDATABASE_TEST: ${{ secrets.PGDATABASE_TEST }}
          PGPASSWORD_TEST: ${{ secrets.PGPASSWORD_TEST }}
          PGPORT_TEST: ${{ secrets.PGPORT_TEST }}
          PGHOST: ${{ secrets.PGHOST_TEST }}
          PGUSER: ${{ secrets.PGUSER_TEST }}
          PGDATABASE: ${{ secrets.PGDATABASE_TEST }}
          PGPASSWORD: ${{ secrets.PGPASSWORD_TEST }}
          PGPORT: ${{ secrets.PGPORT_TEST }}
          ACCESS_TOKEN_KEY: ${{ secrets.ACCESS_TOKEN_KEY }}
          REFRESH_TOKEN_KEY: ${{ secrets.REFRESH_TOKEN_KEY }}
          ACCESS_TOKEN_AGE: ${{ secrets.ACCESS_TOKEN_AGE }}
  deploy:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: SSH and deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app
            git pull origin master
            npm install
            npm run migrate up
            pm2 restart forumapi-prasetya
